---
title: "Ess 330 Project Proposals"
authors:
  - name: Chippy Marx
    affiliation: CSU
    roles: writing
    corresponding: true
  - name: Chris Drew
    affiliation: CSU
    roles: writing

bibliography: references.bib
---

## Idea #1: Carbon storage changes under climate change.

**Research Question**: How does changing climatic conditions affect forest fire projections and carbon storage In the Colorado over the next 5 years?

**Justification**:

Wildfires are affected by climate change, and extreme fires are becoming more frequent due to increased drought, reduced humidity and soil moisture, and changing temperature @wu2023uncertainty . This poses a risk to carbon sequestration by forests, as more extreme fires release stored carbon from these forests; yet in some areas carbon storage is still predicted to increase @shmuel2025global . In Colorado, forest fire is a relevant and important topic, therefor I want to scale data on climate and fire projections and then use that to predict carbon storage changes in Colorado over the next 5 years. This topic is ultimately important because changes in carbon sequestration greatly influence climate change, creating a feedback loop; as fires increase more carbon is on the atmosphere, increasing the effects of climate change, and therefor increasing fire potential @burton2024fire . Fires are currently a threat to global climate change and emission goals because of the loss of carbon in forests, which increases the carbon in the atmosphere @burton2024fire.

**Methods**:

For the analysis of this question, I will use the drought and wildfire data that includes temperature, soil moisture, humidity, wind speed and fuel availability data (https://www.drought.gov/topics/fire). I will use multivariate statistics tests such as an ANOVA test to see how different climatic conditions and fire interact. I will use the climate and fire projections @shmuel2025global and land cover data for the west (from MRLC) to predict carbon storage change over the next 5 years. I will use the paper “Uncertainty in US forest carbon storage potential due to climate risks” to establish the relationship between fire and carbon storage loss @wu2023uncertainty. This paper also has useful information for my calculations and conversions. I will also use data “Fire weakens land carbon sinks before 1.5 °C” @burton2024fire to strengthen the connection between fire and carbon storage. I think that I will know more specifically how I will use them when I dig into the data, but for now I think they are both good resources to have. Ultimately, I will run correlation tests to see how the climatic variables interact with fire and my carbon storage projections.

Expected Outcome: I expect that due to increasingly aray climatic conditions, carbon storage will decrease in Colorado in the next 5 years

## Idea #2: Invasive plant- forest fire feedback loop.

**Research Question**: How do non-native plants effect fire regimes and maintain dominance in Colorado? Justification: Invasive plants and forest fires are significant issues in Western US. Invasions by non-native plant species after fire can negatively impact important ecosystem services and lead to invasion-fire cycles, which ultimately further degrade ecosystems @prevey2024non The impact of non-natives on forest fires is complex and can vary between vegetative functional type and geographic region @prevey2024non . It has been established that native woody species rely on soil microbiomes to establish on burned soil, while non-native do not; this makes non-natives more likely to establish quickly after forest fires and then dominate these disturbed sites @escobedo2024native. However, scientific understanding of how to restore plant-soil microbiome interactions after wildfires remains limited, leading to a key knowledge gap in post- fire ecosystem restoration @escobedo2024native. This topic is ultimately important because it can inform management decisions on how to treat and restore areas pre and post fire in the arid west.

**Methods:** To answer this question, I will use the projections of post fire cover non-native and short-lived species under current and future climate conditions to create a baseline of what invasions will look like in the future @prevey2024non . I will then use the information and data of different geographic regions and vegetative functional type to analyze how the different projected invasions will affect forest fire in the future @prevey2024non. I will use data from a study done in greenhouses that assesses nonnative and native plant survival post fire across different vegetative functional types in order to show how the different functional types of plants native to Colorado may be affected by fire @escobedo2024native. For the functional types of native species in Colorado I will use FIA data from the USDA to show trends ( https://research.fs.usda.gov/products/dataandtools/tools/fia-datamart) . I will also use past wildfire data which is available from the article @prevey2024non to show any correlation between functional plant group type and past forest fires.

Expected outcome: I expect that my research will show a increase in the invasives-fire feedback loop in Colorado, and that native plant distribution will decrease.

## Idea #3 : How Rising Temperatures Change Snowmelt Timing

**Justification:** Snowmelt in alpine areas is a major water source for plants, animals and people. With climate change, warmer temperatures are causing snow to melt earlier @musselman2017 . This can disrupt ecosystems and lead to water shortages downstream @ipcc2021. Understanding these changes can help us plan for water use and protect alpine habitats.s.

**Research Question**: How does warming temperature affect when snow melts in alpine areas? Hypothesis: Warmer temperatures cause snow to melt earlier, shortening the snow season.

**Proposed Methods:** We’ll use snowpack data ( NOAA snowpack data) and temperature data ( from PRISM) for alpine regions in the Western U.S. Snowmelt timing will be tracked from 1980 to 2020, and we’ll look for trends linking higher temperatures to earlier snowmelt.

**Expected Outcomes:** We expect to see snow melting earlier as temperatures rise. This could lead to less water for ecosystems and people, showing the need for better water planning.

## Idea #4 : Fire Recovery in Coastal Shrublands

**Justification:** Coastal shrublands are built to handle fire but frequent more intense fires from climate change could push them past their limit @keeley2016 . Studying how shrubs regenerate after fire especially under tough conditions like drought can help us manage and protect them better @enright2015.

**Research Question**: How do fire severity and rainfall affect shrubland regeneration? Hypothesis: Higher fire severity and less rainfall mean slower regeneration.

**Proposed Methods**: We’ll combine fire data with climate data to study post-fire regrowth in California shrublands. Vegetation recovery could be tracked from satellite images. We’ll use statistical models to figure out how fire and rainfall affect regeneration.

**Expected Outcomes**: Shrublands hit by severe fires and low rainfall will show slower recovery. These findings can guide better fire management and restoration planning.
